import subprocess
import json
import os
import sys
import requests

# Add parent directory to path to import existing scripts
SCRIPTS_PATH = os.path.join(os.path.dirname(__file__), "../../scripts")
sys.path.insert(0, SCRIPTS_PATH)

OUTPUT_FOLDER = os.getenv("OUTPUT_FOLDER", "./output")
HOST_OCR_SERVICE = os.getenv("HOST_OCR_SERVICE", "http://host.docker.internal:5001")
HOST_OCR_TIMEOUT_SECONDS = int(os.getenv("HOST_OCR_TIMEOUT_SECONDS", "1800"))

class OCRService:
    """Service to handle OCR and text correction"""

    @staticmethod
    def run_host_ocr_pipeline(image_path: str) -> dict:
        """
        Call host-side OCR service that runs deep.py on Windows machine
        This avoids Docker container issues with DeepSeek model loading
        """
        print(f"[Pipeline] Attempting to call host OCR service at {HOST_OCR_SERVICE}")
        
        try:
            # Check if file exists
            if not os.path.exists(image_path):
                return {
                    "success": False,
                    "error": f"Image file not found: {image_path}"
                }
            
            # Prepare file for upload
            with open(image_path, 'rb') as f:
                files = {'file': (os.path.basename(image_path), f)}
                
                # Call host service
                response = requests.post(
                    f"{HOST_OCR_SERVICE}/process",
                    files=files,
                    timeout=(10, HOST_OCR_TIMEOUT_SECONDS)
                )
            
            if response.status_code != 200:
                error_msg = response.json().get("error", "Unknown error") if response.text else "Service returned error"
                return {
                    "success": False,
                    "error": f"Host service error: {error_msg}",
                    "details": response.json().get("details", "") if response.text else ""
                }
            
            result = response.json()
            if not isinstance(result, dict):
                return {
                    "success": False,
                    "error": "Host service returned invalid payload",
                    "details": f"Expected JSON object, got: {type(result).__name__}"
                }
            
            if not result.get("success"):
                return {
                    "success": False,
                    "error": result.get("error", "Host service processing failed"),
                    "details": result.get("details", "")
                }
            
            print("[Pipeline] Host OCR service processed successfully")
            debug_log = result.get("debug_log", "")
            if debug_log:
                print("[Pipeline] === Host deep.py log start ===")
                for line in debug_log.splitlines():
                    print(f"[Pipeline][deep.py] {line}")
                print("[Pipeline] === Host deep.py log end ===")
            return {
                "success": True,
                "ocr_text": result.get("ocr_text", ""),
                "corrected_text": result.get("corrected_text", ""),
                "raw_json": result.get("raw_json", {}),
                "correction_success": True,
                "correction_error": None,
                "pipeline_source": "host_deep.py",
                "deep_error": None
            }
            
        except requests.exceptions.ConnectionError:
            print(f"[Pipeline] Host OCR service not available at {HOST_OCR_SERVICE}")
            return {
                "success": False,
                "error": "Host OCR service unavailable",
                "details": f"Could not connect to {HOST_OCR_SERVICE}"
            }
        except Exception as e:
            print(f"[Pipeline] Host OCR service error: {str(e)}")
            return {
                "success": False,
                "error": str(e),
                "details": f"Exception calling host service: {str(e)}"
            }

    @staticmethod
    def run_deep_script_pipeline(image_path: str) -> dict:
        """Run deep.py end-to-end and read output files generated by the script."""
        deep_script = os.path.join(SCRIPTS_PATH, "deep.py")
        if not os.path.exists(deep_script):
            return {
                "success": False,
                "error": f"deep.py not found at {deep_script}"
            }

        env = os.environ.copy()
        env["IMAGE_FILE"] = image_path
        env["OUTPUT_FOLDER"] = OUTPUT_FOLDER

        try:
            completed = subprocess.run(
                [sys.executable, deep_script, image_path],
                cwd=SCRIPTS_PATH,
                env=env,
                capture_output=True,
                text=True,
                check=False
            )

            if completed.returncode != 0:
                return {
                    "success": False,
                    "error": f"deep.py failed with code {completed.returncode}",
                    "details": (completed.stderr or completed.stdout or "").strip()
                }

            validated_json_path = os.path.join(OUTPUT_FOLDER, "validated_clean.json")
            ocr_text_path = os.path.join(OUTPUT_FOLDER, "global_ocr.txt")
            corrected_text_path = os.path.join(OUTPUT_FOLDER, "llm_correct.txt")

            if not os.path.exists(validated_json_path):
                return {
                    "success": False,
                    "error": "validated_clean.json not generated by deep.py"
                }

            with open(validated_json_path, "r", encoding="utf-8") as f:
                validated_json = json.load(f)

            ocr_text = ""
            corrected_text = ""

            if os.path.exists(ocr_text_path):
                with open(ocr_text_path, "r", encoding="utf-8") as f:
                    ocr_text = f.read().strip()

            if os.path.exists(corrected_text_path):
                with open(corrected_text_path, "r", encoding="utf-8") as f:
                    corrected_text = f.read().strip()

            if not corrected_text:
                corrected_text = json.dumps(validated_json, ensure_ascii=False, indent=2)

            return {
                "success": True,
                "ocr_text": ocr_text,
                "corrected_text": corrected_text,
                "raw_json": validated_json,
                "correction_success": True,
                "pipeline_status": "deep_script_completed"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }

    @staticmethod
    @staticmethod
    def process_full_pipeline(image_path: str) -> dict:
        """
        Deep.py-only pipeline.
        Tries host-based deep.py first, then container deep.py.
        """
        print(f"\n[Pipeline] Starting full OCR processing pipeline for: {image_path}")

        # Step 0a: Try host-side deep.py first (runs on Windows machine, avoids Docker issues)
        print("[Pipeline] Step 0a: Attempting host-side deep.py...")
        host_result = OCRService.run_host_ocr_pipeline(image_path)
        if host_result.get("success"):
            print("[Pipeline] Host deep.py succeeded. Using host-based validated_clean.json output.")
            return {
                "success": True,
                "ocr_text": host_result.get("ocr_text", ""),
                "corrected_text": host_result.get("corrected_text", ""),
                "raw_json": host_result.get("raw_json", {}),
                "correction_success": True,
                "correction_error": None,
                "pipeline_source": "host_deep.py",
                "deep_error": None,
                "pipeline_status": "host_deep_completed"
            }
        
        print(f"[Pipeline] Host service unavailable, falling back to container methods: {host_result.get('error')}")
        
        # Step 0b: Try container-based deep.py as fallback
        print("[Pipeline] Step 0b: Running deep.py script pipeline in container...")
        deep_script_result = OCRService.run_deep_script_pipeline(image_path)
        if deep_script_result.get("success"):
            print("[Pipeline] deep.py pipeline complete. Using validated_clean.json output.")
            return {
                "success": True,
                "ocr_text": deep_script_result.get("ocr_text", ""),
                "corrected_text": deep_script_result.get("corrected_text", ""),
                "raw_json": deep_script_result.get("raw_json", {}),
                "correction_success": True,
                "correction_error": None,
                "pipeline_source": "deep.py",
                "deep_error": None,
                "pipeline_status": "deep_script_completed"
            }

        deep_error = deep_script_result.get("details") or deep_script_result.get("error")
        print(f"[Pipeline] deep.py pipeline failed: {deep_script_result.get('error')}")
        print("[Pipeline] No fallback pipeline enabled. deep.py-only mode is active.")

        return {
            "success": False,
            "error": "Deep.py pipeline failed",
            "details": {
                "host_error": host_result.get("details") or host_result.get("error"),
                "container_error": deep_error
            },
            "pipeline_source": "deep.py_only"
        }
